export const api = {
  url: "https://api.openweathermap.org/data/2.5/weather?q=",
  key: "4e5536b1e0f31785b374595576ddf91c",
  metricEndPoint: "&units=metric",
  lang: "&lang=es",
  iconoURL: "https://openweathermap.org/img/wn/",
  pais: "AR",
};

export const provinciasArgentinaArray = [
  { value: "Provincias de Argentina", label: "Buscar por Provincias de Argentina" },
  { value: "Ciudad Autónoma de Buenos Aires", label: "Buenos Aires" },
  { value: "catamarca", label: "Catamarca" },
  { value: "chaco Province", label: "Chaco" },
  { value: "Chubut Province", label: "Chubut" },
  { value: "Córdoba", label: "Córdoba" },
  { value: "corrientes", label: "Corrientes" },
  { value: "Entre Rios", label: "Entre Ríos" },
  { value: "formosa", label: "Formosa" },
  { value: "San Salvador de Jujuy", label: "Jujuy" },
  { value: "La Pampa", label: "La Pampa" },
  { value: "La Rioja", label: "La Rioja" },
  { value: "Mendoza", label: "Mendoza" },
  { value: "misiones", label: "Misiones" },
  { value: "Neuquén Province", label: "Neuquén" },
  { value: "rioNegro", label: "Río Negro" },
  { value: "salta", label: "Salta" },
  { value: "San Juan", label: "San Juan" },
  { value: "san Luis", label: "San Luis" },
  { value: "Santa Cruz Province", label: "Santa Cruz" },
  { value: "Santa Fe", label: "Santa Fe" },
  { value: "Santa Fe", label: "Santiago del Estero" },
  { value: "tierraDelFuego", label: "Tierra del Fuego" },
  { value: "Tucumán Province", label: "Tucumán" },
];

export const paisesAfrica = [ 
  { value: "DZ", label: "Argelia" },
  { value: "AO", label: "Angola" },
  { value: "BJ", label: "Benín" },
  { value: "BW", label: "Botsuana" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "CM", label: "Camerún" },
  { value: "CF", label: "República Centroafricana" },
  { value: "TD", label: "Chad" },
  { value: "KM", label: "Comoras" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "República Democrática del Congo" },
  { value: "CI", label: "Costa de Marfil" },
  { value: "DJ", label: "Yibuti" },
  { value: "EG", label: "Egipto" },
  { value: "GQ", label: "Guinea Ecuatorial" },
  { value: "ER", label: "Eritrea" },
  { value: "ET", label: "Etiopía" },
  { value: "GA", label: "Gabón" },
  { value: "GM", label: "Gambia" },
  { value: "GH", label: "Ghana" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bisáu" },
  { value: "KE", label: "Kenia" },
  { value: "LS", label: "Lesoto" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libia" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malaui" },
  { value: "ML", label: "Malí" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauricio" },
  { value: "MA", label: "Marruecos" },
  { value: "MZ", label: "Mozambique" },
  { value: "NA", label: "Namibia" },
  { value: "NE", label: "Níger" },
  { value: "NG", label: "Nigeria" },
  { value: "RW", label: "Ruanda" },
  { value: "ST", label: "Santo Tomé y Príncipe" },
  { value: "SN", label: "Senegal" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leona" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "Sudáfrica" },
  { value: "SS", label: "Sudán del Sur" },
  { value: "SD", label: "Sudán" },
  { value: "SZ", label: "Esuatini" },
  { value: "TZ", label: "Tanzania" },
  { value: "TG", label: "Togo" },
  { value: "TN", label: "Túnez" },
  { value: "UG", label: "Uganda" },
  { value: "EH", label: "Sáhara Occidental" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabue" },
];

export const paisesAmerica = [
  { value: "AR", label: "Argentina" },
  { value: "BO", label: "Bolivia" },
  { value: "BR", label: "Brasil" },
  { value: "CA", label: "Canadá" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "CR", label: "Costa Rica" },
  { value: "CU", label: "Cuba" },
  { value: "DO", label: "República Dominicana" },
  { value: "EC", label: "Ecuador" },
  { value: "SV", label: "El Salvador" },
  { value: "US", label: "Estados Unidos" },
  { value: "GT", label: "Guatemala" },
  { value: "HN", label: "Honduras" },
  { value: "MX", label: "México" },
  { value: "NI", label: "Nicaragua" },
  { value: "PA", label: "Panamá" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Perú" },
  { value: "PR", label: "Puerto Rico" },
  { value: "UY", label: "Uruguay" },
  { value: "VE", label: "Venezuela" },
  { value: "AG", label: "Antigua y Barbuda" },
  { value: "BS", label: "Bahamas" },
  { value: "BB", label: "Barbados" },
  { value: "BZ", label: "Belice" },
  { value: "DM", label: "Dominica" },
  { value: "GD", label: "Granada" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haití" },
  { value: "JM", label: "Jamaica" },
  { value: "LC", label: "Santa Lucía" },
  { value: "VC", label: "San Vicente y las Granadinas" },
  { value: "SR", label: "Surinam" },
  { value: "TT", label: "Trinidad y Tobago" },
  { value: "UY", label: "Uruguay" },
];

export const paisesAsia = [
  { value: "AF", label: "Afganistán" },
  { value: "AM", label: "Armenia" },
  { value: "AZ", label: "Azerbaiyán" },
  { value: "BH", label: "Baréin" },
  { value: "BD", label: "Bangladés" },
  { value: "BN", label: "Brunéi" },
  { value: "BT", label: "Bután" },
  { value: "CN", label: "China" },
  { value: "GE", label: "Georgia" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Irán" },
  { value: "IQ", label: "Irak" },
  { value: "IL", label: "Israel" },
  { value: "JP", label: "Japón" },
  { value: "JO", label: "Jordania" },
  { value: "KZ", label: "Kazajistán" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kirguistán" },
  { value: "LB", label: "Líbano" },
  { value: "MY", label: "Malasia" },
  { value: "MV", label: "Maldivas" },
  { value: "MN", label: "Mongolia" },
  { value: "MM", label: "Myanmar (Birmania)" },
  { value: "NP", label: "Nepal" },
  { value: "KP", label: "Corea del Norte" },
  { value: "OM", label: "Omán" },
  { value: "PK", label: "Pakistán" },
  { value: "PS", label: "Territorios Palestinos" },
  { value: "PH", label: "Filipinas" },
  { value: "QA", label: "Catar" },
  { value: "SA", label: "Arabia Saudita" },
  { value: "SG", label: "Singapur" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SY", label: "Siria" },
  { value: "TW", label: "Taiwán" },
  { value: "TJ", label: "Tayikistán" },
  { value: "TH", label: "Tailandia" },
  { value: "TR", label: "Turquía" },
  { value: "TM", label: "Turkmenistán" },
  { value: "AE", label: "Emiratos Árabes Unidos" },
  { value: "UZ", label: "Uzbekistán" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
];

export const paisesEuropa = [
  { value: "AL", label: "Albania" },
  { value: "AD", label: "Andorra" },
  { value: "AT", label: "Austria" },
  { value: "BY", label: "Bielorrusia" },
  { value: "BE", label: "Bélgica" },
  { value: "BA", label: "Bosnia y Herzegovina" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croacia" },
  { value: "CY", label: "Chipre" },
  { value: "CZ", label: "República Checa" },
  { value: "DK", label: "Dinamarca" },
  { value: "EE", label: "Estonia" },
  { value: "FI", label: "Finlandia" },
  { value: "FR", label: "Francia" },
  { value: "DE", label: "Alemania" },
  { value: "GR", label: "Grecia" },
  { value: "HU", label: "Hungría" },
  { value: "IS", label: "Islandia" },
  { value: "IE", label: "Irlanda" },
  { value: "IT", label: "Italia" },
  { value: "LV", label: "Letonia" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lituania" },
  { value: "LU", label: "Luxemburgo" },
  { value: "MT", label: "Malta" },
  { value: "MD", label: "Moldavia" },
  { value: "MC", label: "Mónaco" },
  { value: "ME", label: "Montenegro" },
  { value: "NL", label: "Países Bajos" },
  { value: "MK", label: "Macedonia del Norte" },
  { value: "NO", label: "Noruega" },
  { value: "PL", label: "Polonia" },
  { value: "PT", label: "Portugal" },
  { value: "RO", label: "Rumania" },
  { value: "RU", label: "Rusia" },
  { value: "SM", label: "San Marino" },
  { value: "RS", label: "Serbia" },
  { value: "SK", label: "Eslovaquia" },
  { value: "SI", label: "Eslovenia" },
  { value: "ES", label: "España" },
  { value: "SE", label: "Suecia" },
  { value: "CH", label: "Suiza" },
  { value: "UA", label: "Ucrania" },
  { value: "GB", label: "Reino Unido" },
  { value: "VA", label: "Ciudad del Vaticano" },
];

export const paisesOceania = [
  { value: "AS", label: "Samoa Americana" },
  { value: "AU", label: "Australia" },
  { value: "FJ", label: "Fiyi" },
  { value: "KI", label: "Kiribati" },
  { value: "MH", label: "Islas Marshall" },
  { value: "FM", label: "Micronesia" },
  { value: "NR", label: "Nauru" },
  { value: "NZ", label: "Nueva Zelanda" },
  { value: "PW", label: "Palaos" },
  { value: "PG", label: "Papúa Nueva Guinea" },
  { value: "SB", label: "Islas Salomón" },
  { value: "TO", label: "Tonga" },
  { value: "TV", label: "Tuvalu" },
  { value: "VU", label: "Vanuatu" },
];

//console.log('Países de Oceanía:', paisesOceania);

///////////////////////////////////////////////////////////////
// const provinciasArgentina = {
//   BuenosAires: {
//     value: "Ciudad Autónoma de Buenos Aires",
//     label: "Buenos Aires",
//   },
//   Catamarca: { value: "catamarca", label: "Catamarca" },
//   chaco: { value: "chaco", label: "Chaco" },
//   chubut: { value: "chubut", label: "Chubut" },
//   cordoba: { value: "Córdoba", label: "Córdoba" },
//   corrientes: { value: "corrientes", label: "Corrientes" },
//   entreRios: { value: "Entre Ríos", label: "Entre Ríos" },
//   formosa: { value: "formosa", label: "Formosa" },
//   Jujuy: { value: "San Salvador de Jujuy", label: "Jujuy" },
//   laPampa: { value: "Entre Ríos", label: "La Pampa" },
//   laRioja: { value: "La Rioja", label: "La Rioja" },
//   Mendoza: { value: "Mendoza", label: "Mendoza" },
//   misiones: { value: "misiones", label: "Misiones" },
//   neuquen: { value: "neuquén", label: "Neuquén" },
//   rioNegro: { value: "rioNegro", label: "Río Negro" },
//   salta: { value: "salta", label: "Salta" },
//   sanJuan: { value: "San Juan", label: "San Juan" },
//   sanLuis: { value: "san Luis", label: "San Luis" },
//   santaCruz: { value: "Santa Cruz Province", label: "Santa Cruz" },
//   santaFe: { value: "Santa Fe", label: "Santa Fe" },
//   santiagoDelEstero: { value: "Santa Fe", label: "Santiago del Estero" },
//   tierraDelFuego: { value: "tierraDelFuego", label: "Tierra del Fuego" },
//   tucuman: { value: "Tucumán Province", label: "Tucumán" },
// };
//PARA TRANSFORMAR UN OBJ EN UN ARR DE CLAVES Object.keys(OBJETO).forEach.....

// o usar un for in
// for (const key in provinciasArgentina) {
//   if (provinciasArgentina.hasOwnProperty(key)) {
//     const opcion = document.createElement("option");
//     opcion.value = provinciasArgentina[key].value;
//     opcion.textContent = provinciasArgentina[key].label;
//     miSelect.appendChild(opcion);
//   }
// }
